travis:
  secure:
    BINSTAR_TOKEN: W/Qhab50Mf41nXsZbo8y9FqCAi2vv0WVAsyji4YyRdpLbkafH00Cgb1zedWk0jPPThoUk5+qMoyX5W6n0zGrZyQnWbEIbywfH+244JYxaauHZyZ9cAKbUPsQY+T8X0Dut0QTtd52Iuuo8Q1O8QT8k2h0/UD3qncJLXHB/XjA1SGPCDBE7/sM9eJsnKefjz2T3zdU2GFtkFH6RgJK2Ye+LMLT609hlQ44awz86Qs3pHC6DMM64YM5AF8LVopuD/jwpbt6eZOknIWJanCbu9ZGylzOJWDSNEH8NDId0ItNrCfXNFlXHimLrrz3w98SI/DT4VtH45eu2BvGVfp0DdfEqIrbDiep4ph68PDmoTARoc3XFj2TLbUKwLDdB+cORIU50+xEQbTAN+hEw1rI1BUhrOre7vDbn7+QMbaZNGW5e15STTgqgr6aQeRTtXKH2wbNsaEk1lMReYvUIHf9UaaF1zwCm6qhqrWab7w5I6SGK9qqSOSwPZfQXN9Mi6FVr9hbl2uVxbog6+6FmS79s5TtEqXnHdwz1JJxHpJxGxqp1K+QvyeuZeNYDNfQDHxdxnG8evH0Pmx4BaxZET+AwOX/nxrisNbCgsbEVO1sD3raBqQXw8T0VjdI0hubsVrd+qmmoHABlPs2pOn6MqhFsCf8jmF4JArEdhvdb0RDzs8KxVE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
