travis:
  secure:
    BINSTAR_TOKEN: jHS3CfcOc8A9DR3eypJtxLYbJAmboqaA3WH4NC1vZPL6/J4B+pFxxEy6f+DVV+msWhIeew1T9j5iuiMyIQtXhI8W/AosNG7+TFBZsA8IoUUcjO9bqAdlgHmZZPEPtN27FA+NBoKhK9oHjAhvivcjk+XXr+S7zULi25ch7g59Z9NcpWt42ct1EqX+0lJW09184R7Igcj6Gv1gThjeqm4Ssy2VdLsGFR16o2U+wtkY9noaRmcjh8C2mztnjGoGoYQ3d3UUSUyLcNJf9JIsbth1fE9xqP22XGoCti29KRvjSEtH8AaElhOn8KomRGjc6feKJX2kEfIcyvW9s8a25+OABA3rxqPiQHImPZuc4w8RMLkGSIWsH9rZDp7ClJt7V5JzpYWkG72QmgR4g4AIozpfF8p9iLQ4+4O0yqcwKRDD3UNt/P7GIiDACtQqIQpes7DGnTMyk49D3qreAkc2kfEf5De3Y2Epke76DQFaUvUtC+xD4DJvDILMJIN7mLVez7i7sNKW8T5u224wnQvIZvufj3tldSKG55uPNv4+adxC38hmbH+jjy6x+I55UE0ZzxmaczxJg+3rW+hQ9Fyw9A716DjrZkM0DMtx35eLhAQ26iUQHTrxDV7fbpvDcG7s5/bVQL+h5n8EP/KBqgt1nTihZqGSI2AjV0ML//I3Bo5bobc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
